image: tmaier/docker-compose:17.09
services:
  - docker:17.09-dind


stages:
- build
- release


variables:
  CONTAINER_APP_IMAGE: $CI_REGISTRY_IMAGE:app-$CI_COMMIT_REF_SLUG
  CONTAINER_WEB_IMAGE: $CI_REGISTRY_IMAGE:web-$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_APP_IMAGE: $CI_REGISTRY_IMAGE:app-latest
  CONTAINER_RELEASE_WEB_IMAGE: $CI_REGISTRY_IMAGE:web-latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.acolono.net:444

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_APP_IMAGE -f app.dockerfile .
    - docker push $CONTAINER_APP_IMAGE
    - docker build --pull -t $CONTAINER_WEB_IMAGE -f web.dockerfile .
    - docker push $CONTAINER_WEB_IMAGE

release-image:
  stage: release
  script:
    - docker build --pull -t $CONTAINER_RELEASE_APP_IMAGE -f app.dockerfile .
    - docker push $CONTAINER_RELEASE_APP_IMAGE
    - docker build --pull -t $CONTAINER_RELEASE_WEB_IMAGE -f web.dockerfile .
    - docker push $CONTAINER_RELEASE_WEB_IMAGE
  only:
    - master
