version: '2'
services:

  # The Application
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    links:
      - rasa

  # The Web Server
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
     - ./conf/nginx:/etc/nginx/conf.d
     - ./logs/nginx:/var/log/nginx
     - ..:/var/www/html
    volumes_from:
      - app
    ports:
      - 90:90
    depends_on:
      - app
    links:
      - app

  # RASA NLU
  rasa:
    image: registry.acolono.net:444/hoaxly/hoaxly-rasa-nlu-container:latest
    ports:
      - 5000

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"

volumes:
  dbdata:
