version: '2'
services:

  #  The Application
  app:
    image: registry.acolono.net:444/hoaxly/hoaxlybot-container:app-latest
    working_dir: /var/www
    volumes:
      - /var/www/storage
    env_file: '.env'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"
    links:
      - rasa

  # The Web Server
  web:
    image: registry.acolono.net:444/hoaxly/hoaxlybot-container:web-latest
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ..:/var/www/html
      - "${LE_DIR}:/etc/letsencrypt"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    links:
      - app

  # RASA NLU
  rasa:
    image: registry.acolono.net:444/hoaxly/hoaxly-rasa-nlu-container:latest
    ports:
      - 5000

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"

  # redis
  cache:
    image: redis:3.0-alpine

volumes:
  dbdata:
