version: '2'
services:

  #  The Application
  app:
    image: registry.acolono.net:444/hoaxly/hoaxlybot-container:latest
    working_dir: /var/www
    container_name: app
    volumes:
      - /var/www/storage
    env_file: '.env'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"
    links:
      - rasa

  # The Web Server
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ../hoaxlybot/public:/var/www/public
    depends_on:
      - app
    links:
      - app
    environment:
     - NGINX_HOST=chat.hoax.ly
     - NGINX_PORT=80

  # RASA NLU
  rasa:
    image: registry.acolono.net:444/hoaxly/hoaxly-rasa-nlu-container:latest
    ports:
      - 5000

  # The Database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"

  # redis
  cache:
    image: redis:3.0-alpine

volumes:
  dbdata: