version: '2'
services:

  #  The Application
  app:
    image: registry.acolono.net:444/hoaxly/hoaxlybot-container:latest
    working_dir: /var/www
    container_name: app
    restart: always
    volumes:
      - /var/www/storage
      #- ${PROJECT_ROOT}.:/var/www/hoaxlybot
    env_file: '.env'
    environment:
      - "DB_HOST=database"
      - "REDIS_HOST=cache"
    ports:
      - 80:80
    links:
      - rasa
      - database

  # The Web Server
#  web:
#    image: registry.acolono.net:444/hoaxly/hoaxlybot-container:web-latest
#    ports:
#      - 80:80
#    volumes:
#      - ./hoaxlybot/public:/usr/share/nginx/html
#    depends_on:
#      - app
#    links:
#      - app

  # RASA NLU
  rasa:
    image: registry.acolono.net:444/hoaxly/hoaxly-rasa-nlu-container:latest
    container_name: rasa
    restart: always
    ports:
      - 5000:5000

  # The Database
  database:
    image: mysql:5.6
    container_name: database
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"

  # redis
  cache:
    image: redis:3.0-alpine
    restart: always

volumes:
  dbdata:
